	INSERT INTO tb_task_group (description) VALUES
('Project Planning'),
('Requirement Analysis'),
('Design and Development'),
('Quality Assurance'),
('Deployment and Testing'),
('Documentation'),
('Project Review'),
('Client Communication'),
('Resource Allocation'),
('Risk Management'),
('Team Coordination'),
('Vendor Management'),
('Stakeholder Meetings'),
('Progress Reporting'),
('User Training'),
('Change Management'),
('Cost Estimation'),
('Scheduling'),
('Scope Management'),
('Issue Resolution'),
('Task Prioritization'),
('Milestone Tracking'),
('Status Reporting'),
('Budget Management'),
('Procurement Management'),
('Resource Hiring'),
('Contract Management'),
('Integration Management'),
('Communication Planning'),
('Conflict Resolution'),
('Client Feedback'),
('Technical Support'),
('User Acceptance Testing'),
('Data Analysis'),
('Infrastructure Setup'),
('Security Assessment'),
('Performance Monitoring'),
('Feedback Collection'),
('Market Research'),
('Product Launch'),
('Marketing and Promotion'),
('Market Analysis'),
('Legal Compliance'),
('Regulatory Approval'),
('Resource Planning'),
('Knowledge Transfer'),
('Training and Development'),
('Innovation Management');
